### ISSUE TITLE
Dockerfile build error

### ISSUE THREAD

**Issue by dbc-yos-nit** [tpaviot/pythonocc-binderhub#1]
I am trying build Dockerfile.
but I get error message below.

Step 56/64 : RUN /opt/conda/bin/pip install --user -e .
 ---> Running in 8d40f710c4c0
Obtaining file:///opt/build/pythreejs
    Complete output from command python setup.py egg_info:
    setup.py entered
    $PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    running egg_info
    creating pythreejs.egg-info
    error: could not create 'pythreejs.egg-info': Permission denied
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /opt/build/pythreejs/
The command '/bin/sh -c /opt/conda/bin/pip install --user -e .' returned a non-zero code: 1

**Comment by tpaviot** [comment]
Deprecated.
