### ISSUE TITLE
Docker build failing at [22/38] - [24/38] in Step [64/72] RUN ninja install

### ISSUE THREAD

**Issue by MS-cognify** [tpaviot/pythonocc-binderhub#6]
After running for about 2.5h the build terminated. 
The attached file should clearify where things went wrong.
Focused on the last parts where errors occured:
[Error_Docker_build.txt](https://github.com/tpaviot/pythonocc-binderhub/files/3176511/Error_Docker_build.txt)

The whole thing:
[Full_Report.txt](https://github.com/tpaviot/pythonocc-binderhub/files/3176541/Full_Report.txt)

**Comment by tpaviot** [comment]
Deprecated.
