### ISSUE TITLE
Fails at step 35/61

### ISSUE THREAD

**Issue by sfornengo** [tpaviot/pythonocc-binderhub#8]
Step 35/61 : RUN git checkout review/occt7x-support
 ---> Running in 64fbae80de55
error: pathspec 'review/occt7x-support' did not match any file(s) known to git.
ERROR: Service 'occ' failed to build: The command '/bin/sh -c git checkout review/occt7x-support' returned a non-zero code: 1

**Comment by tpaviot** [comment]
The branch review/occt7x-support does not exist anymore on pythonocc-core.
